concurrent = 10
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "example (on-prem, docker sock)"
  url = "https://example.com/"
  token = "smthnigntokernfsdf"
  executor = "docker"
#  environment = ["HTTP_PROXY=example.com:3128", "HTTPS_PROXY=example.com:3128", "NO_PROXY=localhost,127.0.0.1,*.example.com,*.example.com,10.0.0.0/8"]
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:git"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/drive/0/gitlab-runner/cache:/cache", "/drive/0/gitlab-runner/builds:/builds", "/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0