version: "3"
services:
  elastic:
    image: elasticsearch:8.4.3
    container_name: elastic
    network_mode: host
    environment:
      - discovery.type=single-node
      # - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=kibana
      - ELASTIC_USERNAME=kibana
      - xpack.security.enabled=false
      # - node.name=es01
      # - cluster.name=es-docker-cluster
      # - discovery.seed_hosts=es02,es03
      # - cluster.initial_master_nodes=es01
      # - network.host=0.0.0.0
      # - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: kibana:8.4.3
    network_mode: host
    environment:
      # - ELASTICSEARCH_USERNAME=elastic
      # - ELASTICSEARCH_PASSWORD=elastic
      - SERVER_HOST="127.0.0.1"
      # - ELASTIC_CONTAINER="true"
      - ELASTICSEARCH_HOSTS="http://127.0.0.1:9200"
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=password
      - xpack.security.enabled=false
      # - xpack.security.encryptionKey="something_at_least_32_characters"
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 0.0.0.0:5601:5601
    depends_on:
      - elastic




