version: '3.3'

networks:
  default:
    external:
      name: localdev

services:
  jiralert:
    image: jiralert:notifier
    container_name: prometheus-jiralert
    volumes:
      - /opt/jiralert:/config
    command:
      - '--config.file=/conifg/jiralert.yml'
    ports:
      - 0.0.0.0:9097:9097
    restart: always